[build.environment]
  NETLIFY_USE_YARN = "true"
  YARN_VERSION = "1.22.17"

[build]
  base = "site"
  command = "yarn build"
  publish = "site/dist"

[context.deploy-preview]
  command = "yarn build:preview"

[dev]
  framework = "hugo"
  targetPort = 3000
